# =============================================================================
# Fail2Ban - Filtro para autenticación de Traefik
# =============================================================================

[Definition]
failregex = ^<HOST> - .* "(GET|POST|HEAD).*" (401|403) .*$
ignoreregex =
